server:
  port: 8700
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul"
    username: "root"
    password: "8384"
  driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: store-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
